#!/bin/bash

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postinst.d && run-parts --arg="5.18.5-rk3399" --arg="/boot/vmlinuz-5.18.5-rk3399" /etc/kernel/postinst.d

ln -sf vmlinuz-5.18.5-rk3399 /boot/Image 2> /dev/null || mv /boot/vmlinuz-5.18.5-rk3399 /boot/Image
touch /boot/.next
exit 0
