#!/bin/bash

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/prerm.d && run-parts --arg="5.18.5-rk3399" --arg="/boot/vmlinuz-5.18.5-rk3399" /etc/kernel/prerm.d
exit 0
